name: Upload report to GitHub pages

on:
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0
    - run: npx radius-tracker timelines ./config.js
    - run: npx radius-tracker report
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: radius-tracker-report
        branch: gh-pages
        token: ${{secrets.GITHUB_TOKEN}}
