name: Artifact upload example

on:
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0
    - run: npx radius-tracker timelines ./config.js
    - run: npx radius-tracker report
    - uses: actions/upload-artifact@v3
      with:
        name: tracker-report
        path: radius-tracker-report/*
